#!/usr/bin/env bash

# Copyright (c) 2015 - 2018, Hassan Salehe Matar
# All rights reserved.
#
# This file is part of DFinspec. For details, see
# https://github.com/hassansalehe/DFinspec.
#

HOME=`pwd`

# Benchmarks-related directories
BENCHS_DIR=$HOME/benchmarks
SRC=$BENCHS_DIR/src
INC=$BENCHS_DIR/include
STMSTL=$BENCHS_DIR/include/stm_stl
ATOMICOPS=$BENCHS_DIR/include/atomic_ops
TMMISC=$BENCHS_DIR/tmmisc

# Instrumentation directory
INSTR_DIR=$HOME/instrumentor
BIN_DIR=$HOME/bin

# The usage function, details how to use this tool
Usage() {
  echo "Usage:"
  echo "  $ dfinspec <source_code_file> <gcc/clang_compiler_parameters>"
  echo "    e.g. dfinspec src/tests/parallel.c -g"
  echo ""
  echo ""
}

if [ $# -eq 0 ]; then
  # Error: no arguments
  Usage
  exit 1
elif [ $1 == "--help" ]; then
  # User needs help message
  Usage
  exit 0
elif [ $1 == "--tests" ]; then

  # Compile the tests found in src/tests
  FILES=($(egrep -l "main.*(.*)" src/tests/*.c))

  for file in "${FILES[@]}"; do
    echo -e "\033[1;32mTranslating $file\033[m"
    execbin="$(basename "$file").exe"

    clang++ -Xclang -load -Xclang $BIN_DIR/libADFInstrumentPass.so	\
	-I${SRC} -I${INC} -I${STMSTL} -I${ATOMICOPS} -I${TMMISC} 	\
	-DADF_STM -DADF -g -Wall -O0 -std=c++11 -pthread -lsfftw -litm	\
	"$@" -L${BIN_DIR} -lCallbacks -lLogger -L${BENCHS_DIR}/lib 	\
	-ladf "${file}"

    echo
    ./$execbin # execute the compiled program
    echo
  done
else

    clang++ -Xclang -load -Xclang $BIN_DIR/libADFInstrumentationPass.so	\
 	-I${SRC} -I${INC} -I${STMSTL} -I${ATOMICOPS} -I${TMMISC} 	\
	-DADF_STM -DADF -g -Wall -O0 -std=c++11 -pthread -lsfftw -litm	\
	${BIN_DIR}/Callbacks.o ${BIN_DIR}/Logger.o -L${BENCHS_DIR}/lib 	\
	${BENCHS_DIR}/obj/adf/adf.o -ladf "$@"
fi
