#!/usr/bin/env bash

# Copyright (c) 2017, Hassan Salehe Matar
# All rights reserved.
#
# This file is part of DFinspec. For details, see
# https://github.com/hassansalehe/DFinspec.
#

HOME=`pwd`
BIN_DIR=$HOME/bin
OPENMP_DIR=$BIN_DIR

# The usage function, details how to use this tool
Usage() {
  echo "Usage:"
  echo "  $ dfinspec <option> <source_code_file> <gcc/clang_compiler_parameters>"
  echo "    e.g. dfinspec --openmp src/tests/parallel.c -g"
  echo ""
  echo "   <option> can be one of the follwing:"
  echo ""
  echo "   --help"
  echo "   prints this help message."
  echo ""
  echo "   --openmp"
  echo "   for detecting nondeterminism in OpenMP programs."
  echo ""
  echo "   --adf"
  echo "   for detecting nondeterminism in ADF programs."
  echo ""
}

if [ $# -eq 0 ]; then
  # Error: no arguments
  Usage
  exit 1
elif [ $1 == "--help" ]; then
  # User needs help message
  Usage
  exit 0
elif [ $1 == "--openmp" ]; then

  shift

  clang++ -Xclang -load -Xclang ${BIN_DIR}/libOpenMPInstrumentPass.so	\
      -g -Wall -O0 -I${OPENMP_DIR}/include -L${OPENMP_DIR}/lib		\
      -Wl,--rpath,${OPENMP_DIR}/lib -fopenmp --std=c++11 -pthread "$@"	\
      -L${BIN_DIR} -lOpenmpCallbacks -pthread

elif [ $1 == "--adf" ]; then

  shift
  if [ $# -eq 0 ]; then
    echo "Error: no source file supplied"
    Usage
    exit 1
  fi
  ## Benchmarks-related directories ##
  BENCHS_DIR=$HOME/src/tests/adf_benchmarks
  SRC=$BENCHS_DIR/src
  INC=$BENCHS_DIR/include
  STMSTL=$BENCHS_DIR/include/stm_stl
  ATOMICOPS=$BENCHS_DIR/include/atomic_ops
  TMMISC=$BENCHS_DIR/tmmisc

  clang++ -Xclang -load -Xclang $BIN_DIR/libADFInstrumentPass.so	\
	-I${SRC} -I${INC} -I${STMSTL} -I${ATOMICOPS} -I${TMMISC} 	\
	-DADF_STM -DADF -g -Wall -O0 -std=c++11 -pthread -lsfftw -litm	\
	"$@" -L${BIN_DIR} -lCallbacks -lLogger -L${BENCHS_DIR}/lib 	\
	-ladf

else
  echo "Unknown arguments"
  Usage
fi
